const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Plugins.Particles,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Exps.InitSpeed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{btn_play: 0},
	{btn_pause: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{spr_control: 0},
	{spr_player: 0},
	{par_Player: 0},
	{par_players_parts: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{spr_player_parts: 0},
	{spr_enemy: 0},
	{par_Enemy: 0},
	{par_enemy_parts: 0},
	{spr_enemy_parts: 0},
	{Tween: 0},
	{spr_fade: 0},
	{spr_enemyDetectors: 0},
	{txt_score: 0},
	{txt_high_score: 0},
	{gamePaused: 0},
	{score: 0},
	{isAlive: 0},
	{highScore: 0},
	{enemySpeed: 0},
	{enemyFrequency: 0}
];

self.InstanceType = {
	btn_play: class extends self.ISpriteInstance {},
	btn_pause: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	spr_control: class extends self.ISpriteInstance {},
	spr_player: class extends self.ISpriteInstance {},
	par_Player: class extends self.IParticlesInstance {},
	par_players_parts: class extends self.IParticlesInstance {},
	spr_player_parts: class extends self.ISpriteInstance {},
	spr_enemy: class extends self.ISpriteInstance {},
	par_Enemy: class extends self.IParticlesInstance {},
	par_enemy_parts: class extends self.IParticlesInstance {},
	spr_enemy_parts: class extends self.ISpriteInstance {},
	spr_fade: class extends self.ISpriteInstance {},
	spr_enemyDetectors: class extends self.ISpriteInstance {},
	txt_score: class extends self.ITextInstance {},
	txt_high_score: class extends self.ITextInstance {}
}